#train: ../data/train/images
train: ../data/synthetic/images
test: ../data/test/images
val: ../data/valid/images

source: https://universe.roboflow.com/ibnu-h3cda/avocado-g9fsl

nc: 1
names: ['aguacate_hass']